# Generated by Django 5.2.11 on 2026-03-25 17:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du rapport')),
                ('file', models.FileField(upload_to='reports/', verbose_name='Fichier (PDF/Image)')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de téléchargement')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'Traitement en cours'), ('COMPLETED', 'Terminé'), ('FAILED', 'Échec')], default='PENDING', max_length=20)),
                ('processed_text', models.TextField(blank=True, null=True, verbose_name='Texte extrait')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
