# Generated by Django 5.2.11 on 2026-04-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_rapportheader_rapportresultat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'Traitement en cours'), ('COMPLETED', 'Terminé'), ('FAILED', 'Échec'), ('REFUSED', 'Refusé')], default='PENDING', max_length=20),
        ),
    ]
