# Generated by Django 5.2.11 on 2026-04-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_add_refused_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportheader',
            name='date_emission',
            field=models.DateField(blank=True, max_length=255, verbose_name="Date d'émission"),
        ),
    ]
