# Generated by Django 5.2.11 on 2026-04-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_rapportheader_date_emission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportheader',
            name='date_emission',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'émission"),
        ),
    ]
