# Generated by Django 5.2.11 on 2026-04-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_rapportheader_date_emission'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportresultat',
            name='methode_essai',
            field=models.CharField(blank=True, max_length=300, verbose_name="Méthode d'essai"),
        ),
    ]
