# Generated by Django 5.2.11 on 2026-04-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_rapportresultat_methode_essai'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportheader',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé'),
        ),
        migrations.AddField(
            model_name='rapportresultat',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé'),
        ),
    ]
