# Generated by Django 5.2.11 on 2026-04-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_add_is_deleted_to_header_and_resultat'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé'),
        ),
    ]
